spring.application.name=UniLingo
spring.datasource.url=jdbc:mysql://localhost:3306/unilingo
spring.datasource.username=root
spring.datasource.password=root_daria

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.docker.compose.enabled=false